DROP TABLE   B_USER_INFO  ;

CREATE TABLE   B_USER_INFO   (
	  USER_ID  	VARCHAR2(20)		NOT NULL,
	  USER_PASSWORD  	VARCHAR2(16)		NOT NULL,
	  USER_NAME  	VARCHAR2(100)		NOT NULL,
	  USER_EMAIL  	VARCHAR2(100)		NOT NULL,
	  USER_BIRTHDAY  	VARCHAR2(8)		NOT NULL,
	  GENDER  	NUMBER		NOT NULL,
	  USER_TEL  	VARCHAR2(13)		NOT NULL,
	  USER_POST  	VARCHAR2(15)		NOT NULL,
	  USER_ADDRESS  	CLOB		NOT NULL
);

DROP TABLE   B_POSTS  ;

CREATE TABLE   B_POSTS   (
	  POST_NO  	NUMBER		NOT NULL,
	  USER_ID  	VARCHAR2(20)		NOT NULL,
	  CONTENT  	CLOB		NOT NULL,
	  POST_REG_DATE  	DATE	DEFAULT SYSDATE	NOT NULL,
	  POST_TITLE  	VARCHAR2(100)		NOT NULL,
	  POST_PERMISSION  	NUMBER		NOT NULL,
	  POST_HIT  	NUMBER		NOT NULL
);

DROP TABLE   B_PRODUCTS  ;

CREATE TABLE   B_PRODUCTS   (
	  PRODUCT_NAME  	VARCHAR2(100)		NOT NULL,
	  PRODUCT_TYPE  	VARCHAR2(10)		NOT NULL,
	  RELEASE_DATE  	DATE	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL,
	  END_DATE  	DATE		NOT NULL,
	  PRODUCT_RATE  	NUMBER		NOT NULL
);

DROP TABLE   B_ACCOUNT  ;

CREATE TABLE   B_ACCOUNT   (
	  ACC_NO  	VARCHAR2(50)		NOT NULL,
	  USER_ID  	VARCHAR2(20)		NOT NULL,
	  PRODUCT_NAME  	VARCHAR2(100)		NOT NULL,
	  BANK_CD  	VARCHAR2(20)		NOT NULL,
	  ACC_TYPE  	VARCHAR2(100)		NOT NULL,
	  DORMANT_ACC  	NUMBER(1)	DEFAULT 0	NOT NULL,
	  BALANCE  	NUMBER		NOT NULL,
	  ACC_CREATED_DATE  	DATE	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL,
	  ACC_PASSWORD  	VARCHAR2(6)		NOT NULL
);

DROP TABLE   B_COMMENTS  ;

CREATE TABLE   B_COMMENTS   (
	  COMMENT_NO  	VARCHAR(255)		NOT NULL,
	  POST_NO  	NUMBER		NOT NULL,
	  USER_ID  	VARCHAR2(20)		NOT NULL,
	  COMMENTS  	VARCHAR(255)		NOT NULL,
	  CMT_REG_DATE  	DATE	DEFAULT SYSDATE	NOT NULL
);

DROP TABLE   B_kakao_USER  ;

CREATE TABLE   B_kakao_USER   (
	  kakao_TOKEN  	VARCHAR2(200)		NOT NULL,
	  USER_ID  	VARCHAR2(20)		NOT NULL
);

DROP TABLE   B_TRANSACTION  ;

CREATE TABLE   B_TRANSACTION   (
	  T_CD  	NUMBER		NOT NULL,
	  ACC_NO  	VARCHAR2(50)		NOT NULL,
	  T_DATE  	DATE	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL,
	  T_TYPE  	VARCHAR2(10)		NOT NULL,
	  T_AMOUNT  	NUMBER		NOT NULL,
	  T_INFO  	CLOB		NOT NULL,
	  BANK_CD  	VARCHAR2(20)		NOT NULL
);

DROP TABLE   BANK_INFO  ;

CREATE TABLE   BANK_INFO   (
	  BANK_CD  	VARCHAR2(20)		NOT NULL,
	  BANK_NM  	VARCHAR2(100)		NOT NULL
);

ALTER TABLE   B_USER_INFO   ADD CONSTRAINT   PK_B_USER_INFO   PRIMARY KEY (
	  USER_ID  
);

ALTER TABLE   B_POSTS   ADD CONSTRAINT   PK_B_POSTS   PRIMARY KEY (
	  POST_NO  
);

ALTER TABLE   B_PRODUCTS   ADD CONSTRAINT   PK_B_PRODUCTS   PRIMARY KEY (
	  PRODUCT_NAME  
);

ALTER TABLE   B_ACCOUNT   ADD CONSTRAINT   PK_B_ACCOUNT   PRIMARY KEY (
	  ACC_NO  
);

ALTER TABLE   B_COMMENTS   ADD CONSTRAINT   PK_B_COMMENTS   PRIMARY KEY (
	  COMMENT_NO  
);

ALTER TABLE   B_kakao_USER   ADD CONSTRAINT   PK_B_KAKAO_USER   PRIMARY KEY (
	  kakao_TOKEN  
);

ALTER TABLE   B_TRANSACTION   ADD CONSTRAINT   PK_B_TRANSACTION   PRIMARY KEY (
	  T_CD  
);

ALTER TABLE   BANK_INFO   ADD CONSTRAINT   PK_BANK_INFO   PRIMARY KEY (
	  BANK_CD  
);

ALTER TABLE   B_POSTS   ADD CONSTRAINT   FK_B_USER_INFO_TO_B_POSTS_1   FOREIGN KEY (
	  USER_ID  
)
REFERENCES   B_USER_INFO   (
	  USER_ID  
);

ALTER TABLE   B_ACCOUNT   ADD CONSTRAINT   FK_B_USER_INFO_TO_B_ACCOUNT_1   FOREIGN KEY (
	  USER_ID  
)
REFERENCES   B_USER_INFO   (
	  USER_ID  
);

ALTER TABLE   B_ACCOUNT   ADD CONSTRAINT   FK_B_PRODUCTS_TO_B_ACCOUNT_1   FOREIGN KEY (
	  PRODUCT_NAME  
)
REFERENCES   B_PRODUCTS   (
	  PRODUCT_NAME  
);

ALTER TABLE   B_ACCOUNT   ADD CONSTRAINT   FK_BANK_INFO_TO_B_ACCOUNT_1   FOREIGN KEY (
	  BANK_CD  
)
REFERENCES   BANK_INFO   (
	  BANK_CD  
);

ALTER TABLE   B_COMMENTS   ADD CONSTRAINT   FK_B_POSTS_TO_B_COMMENTS_1   FOREIGN KEY (
	  POST_NO  
)
REFERENCES   B_POSTS   (
	  POST_NO  
);

ALTER TABLE   B_COMMENTS   ADD CONSTRAINT   FK_B_USER_INFO_TO_B_COMMENTS_1   FOREIGN KEY (
	  USER_ID  
)
REFERENCES   B_USER_INFO   (
	  USER_ID  
);

ALTER TABLE   B_kakao_USER   ADD CONSTRAINT   FK_B_USER_INFO_TO_B_kakao_USER_1   FOREIGN KEY (
	  USER_ID  
)
REFERENCES   B_USER_INFO   (
	  USER_ID  
);

ALTER TABLE   B_TRANSACTION   ADD CONSTRAINT   FK_B_ACCOUNT_TO_B_TRANSACTION_1   FOREIGN KEY (
	  ACC_NO  
)
REFERENCES   B_ACCOUNT   (
	  ACC_NO  
);

ALTER TABLE   B_TRANSACTION   ADD CONSTRAINT   FK_BANK_INFO_TO_B_TRANSACTION_1   FOREIGN KEY (
	  BANK_CD  
)
REFERENCES   BANK_INFO   (
	  BANK_CD  
);

select * from b_user_info;

select * from b_posts;

CREATE SEQUENCE sequence_postNo nocache;

alter table b_products modify (end_date null);

select * from b_products;


commit;

